### ISSUE TITLE
Category filter on Upcoming events page does not work correctly

### ISSUE THREAD

**Issue by nyenyo** [ArloSoftware/arlowp-plugin#132]
When you go to upcoming events page and filter using the category filter, the page reloads but 
1. it does not really filter anything. still shows all events
2. the selected option on the dropdown, resets to "All categories"
3. when you do it after using the other filters, it resets all selected filters

**Comment by fentosi** [comment]
@nyenyo couldn't reproduce neither on my dev env nor the testautomation site
