### ISSUE TITLE
Different schedule displayed on same live online event

### ISSUE THREAD

**Issue by nyenyo** [ArloSoftware/arlowp-plugin#135]
http://testautomation.cloudsites.excitedmedia.com/events/8-z-regions_-basic-live-online/region-NZ/?timezone=78

https://qatestmr.arlo.co/nz/courses/8-z-regions_-basic-live-online

On both pages, i tried the (GMT+07:00) Krasnoyarsk Timezone and both displayed different event schedules.

Is it because of the difference of arrangements of the timezones?

**Comment by nyenyo** [comment]
Cant see issue when i used NZDT, UK Timezone,

**Comment by fentosi** [comment]
Need to check this again, the whole time zone part has been changed

**Comment by gabriel-arlo** [comment]
Closed as outdated.
