### ISSUE TITLE
Register interest link on similar courses section always redirects to primary region

### ISSUE THREAD

**Issue by nyenyo** [ArloSoftware/arlowp-plugin#136]
On an event where there is an item on the similar courses, and a Register interest link is available, click the link

BUG:
It should redirect to currently selected region. Right now it always redirects to the primary region's register interest page

**Comment by fentosi** [comment]
The [arlo_suggest_template] has an option called "regionalized", if it has been set to "true", that means the shortcode will only show similar events from the selected region. If it hasn't been set, it shows templates from all the available region.

**Comment by nyenyo** [comment]
Update: 
tried using 'regionalised' option set to true - still displays register links pointing to primary region
