### ISSUE TITLE
1 template isn't displayed on the Event catalogue page

### ISSUE THREAD

**Issue by nyenyo** [ArloSoftware/arlowp-plugin#137]
I've checked the templates displayed on the catalogue page and compared with the platform's template list and found that one isn't shown on WP Catalogue page. 

https://my.arlo.co/qatestmr/Console/#/events/24
http://testautomation.cloudsites.excitedmedia.com/events/region-NZ/

That one has correct settings (Published, displayed on website)

**Comment by fentosi** [comment]
It's under "Accounting courses" category

**Comment by nyenyo** [comment]
Found out this happens because the template is on a child category. As per Adam, this isn't a bug - that the list is currently configured to only display templates on a parent category and those without categories.

Closing...
