### ISSUE TITLE
WP Venues page not showing scheduled or upcoming

### ISSUE THREAD

**Issue by Monty9120** [ArloSoftware/arlowp-plugin#451]
"Online" venues are not hyperlinked on event pages in the plugin.
![image](https://user-images.githubusercontent.com/42326561/92534511-1d0c2d00-f289-11ea-9030-d8a3f12c51d9.png)
![image](https://user-images.githubusercontent.com/42326561/92534572-3e6d1900-f289-11ea-98fd-1a75b15f3317.png)

This also means the 'View upcoming' / 'View scheduled' buttons on the venue list page render no results, even though there should be results.

![image](https://user-images.githubusercontent.com/42326561/92534598-50e75280-f289-11ea-8b30-c1907038f908.png)

​

​​

**Comment by ry167** [comment]
#51827 in TFS
