### ISSUE TITLE
Synchronization failed - import callback did not happen

### ISSUE THREAD

**Issue by devinswett** [ArloSoftware/arlowp-plugin#455]
Hello!

I've installed the plugin and have set it up with my Arlo domain, but whenever I attempt to synchronize I get an error, the Synchronization Failed. 

When I check the log I see:

78 | 15364774 | Synchronization failed, please check the Log | 2020-11-06 20:16:16
77 | 15364774 | The import callback did not happen | 2020-11-06 20:16:16
76 | 15364774 | Maximum retry attempt reached for 'Download snapshot file' | 2020-11-06 20:16:16
75 | 15364774 | The import callback did not happen | 2020-11-06 20:16:16

Any advice on the issue would be greatly appreciated.

Thank you!

**Comment by ry167** [comment]
This is generally an issue with your hosting provider or setup. 
Could you contact Arlo Support by submitting a ticket: https://support.arlo.co/hc/en-gb/requests/new
We can help you resolve it there. Thanks
