### ISSUE TITLE
API Calls check 

### ISSUE THREAD

**Issue by ArloSoftwareTeam** [ArloSoftware/arlowp-plugin#54]
need to add the paging (NextPageUri)

**Comment by ArloSoftwareTeam** [comment]
the standard way to do paging is to use the includeTotalCount param and calculate the number of required calls up front (which you can then execute all at once in parallel)
I wouldn't recommend using the NextPageUri for an actual call as it suggests your API calls run in serial rather than parallel

**Comment by fentosi** [comment]
The import has changed since, not an issue anymore
